# Generated by Django 5.1.7 on 2025-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='text_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
