# Generated by Django 5.1.7 on 2025-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_answerchoice_text_en_answerchoice_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
