# Generated by Django 5.1.7 on 2025-03-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_link', models.URLField(unique=True)),
                ('card_number', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
